#!/usr/bin/php
<?php
/**
 * 
 */

// Tampilkan Deskripsi, Penggunaan, Opsi
if ($argc == 1 || in_array($argv[1], array( '--help', '-h' ))) { ?>

# =============================================================================
Deskripsi :

Program shell iseng-iseng untuk mengganti nama-nama file yang terdapat
pada folder
# =============================================================================

Options:
-z
    --prepend-zero  Menambahkan angka `0` sebelum nama file yang memiliki angka
                    dibawah 10
-h
    --help          Tampilkan pesan ini
-v
    --verbose       Verbose

<?php
// Proses eksekusi program
} else {
    // Deklarasi Options
    $s_opt = 'z::a::h::v::';
    $l_opt = array(
        'prepend-zero::',
        'append::',
        'help::',
        'verbose::'
    );
    $options = getopt($s_opt, $l_opt);

    // Ambil informasi direktori
    $dirname = shell_exec('pwd');
    $filenames = shell_exec('ls');
    $dir = opendir(trim($dirname));
    $files = scandir(trim($dirname));

    if (count($files) <= 2) {
        print "Direktori kosyong berooo.... :p\n";
    }

    // Eksekusi pilihan opsi
    if (in_array($argv[1], array( '-z', '--prepend-zero' ))) {

        /**
         * Proses eksekusi opsi -z atau --prepend-zero
         *
         * Proses ini menambahkan angka 0 pada setiap file yang memiliki
         * nama file 1 hingga 9
         */
        foreach ($files as $file) {
            $ext = pathinfo($file, PATHINFO_EXTENSION);
            $name = (int) pathinfo($file, PATHINFO_FILENAME);
            if ($name < 10 && is_file($file)) {
                $new = '0' .$name . '.' . strtolower($ext);
                $status = shell_exec('mv -v ' . $file . ' ' . $new);
                if (isset($options['v']) || isset($options['verbose'])) {
                    print "Ganti $file menjadi $new [OK]\n";
                }
            }
        }

    }
}
?>